### ISSUE TITLE
Filtering update root actions

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/gumtree-spoon-ast-diff#114]
Hi,

It seems that for all types of operations, some filters are applied on allOperations to find the rootOperations. But there is no filter on update operations. See [HERE](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/diff/ActionClassifier.java#L73).

As a result, a change like [THIS ](https://github.com/SpoonLabs/astor-experiments/tree/master/cardumen-patches/unformatted-patches/Math/Math28#patch-diff-3) is considered as a change with two root operations: one Invocation update (`minRatioPositions.add->Precision.equals`) and one VariableRead update (`minRatioPositions->entry`). 

Do you not think that the following filter should be added to [this line](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/diff/ActionClassifier.java#L73)?

`.filter(t -> !srcUpdTrees.contains(t.getParent()))
`
Thanks, @monperrus @martinezmatias

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

> It seems that for all types of operations, some filters are applied on allOperations to find the rootOperations. But there is no filter on update operations. 

Updates are not "grouped" into roots for one reason: an update is an operation that only affects the label of one single node. On the contrary, add or remove operation probably affects several nodes. If you remove one node, it means that you are removing also all children. (Disclaimer: You can also remove a single node and move the children).
For this reason, each update appears on the root list.

> Do you not think that the following filter should be added to this line?
I would say `no`, Updates ops are independent.

**Comment by khaes-kth** [comment]
Good, thanks.
