### ISSUE TITLE
Could I use a diff file as input instead of two program versions?

### ISSUE THREAD

**Issue by bqcuong** [SpoonLabs/gumtree-spoon-ast-diff#123]
Hi,

I wanna ask for using a `.diff` file as input to compute change actions.

I am developing a tool that uses change actions from repository history (i.e. commits).
But sometimes, it is hard to specify the before and after versions of a program.
E.g: I want to collect all the change actions in this pull request of your repo: https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/85
It's kind of complicated to traversal every single commits and collect change actions for each source file.

Instead, I can easily get a diff file for that pull request at: https://patch-diff.githubusercontent.com/raw/SpoonLabs/gumtree-spoon-ast-diff/pull/85.diff

So that, Is it possible to use a diff file instead specific versions to compute change actions?

Thanks a lot,
Cuong

**Comment by martinezmatias** [comment]
Hi @bqcuong 

For the moment we have not implemented that feature yet.
We agree that it would be a very useful feature.

Regards
Matias

**Comment by bqcuong** [comment]
Hi @martinezmatias,

Thank you for your prompt reply.
I hope to see this feature soon in your next releases.

Regards,
Cuong
