### ISSUE TITLE
Get all change actions at statement level or on specific line

### ISSUE THREAD

**Issue by bqcuong** [SpoonLabs/gumtree-spoon-ast-diff#124]
Hi,

I will explain my question/issue through an example. Please look below.
I have two versions of a program:

Origin:
```java
public class Test {
    public static final String FILE_NAME = "testng-results.xml";
    public void f() {
        Utils.writeUtf8File(config.getOutputDirectory(), FILE_NAME, rootBuffer, null /* no prefix */);
    }
}
```

Edited:
```java
public class Test {
    public static final String FILE_NAME = "testng-results.xml";
    public String fileName() {
        return FILE_NAME;
    }
    public void f() {
        Utils.writeUtf8File(config.getOutputDirectory(), fileName(), rootBuffer, null /* no prefix */);
    }
}
```

And GumTree Spoon AST Diff gives me these root operations:
```
Delete FieldRead at Test:4
	Test.FILE_NAME

Insert Method at Test:3
	public java.lang.String fileName() {
	    return Test.FILE_NAME;
	}

Insert Invocation at Test:7
	fileName()
```

Let focus on changes of `Utils.writeUtf8File`. I wanna to collect all change actions on this statement (on line 7 of the edited version). i.e. `Insert Invocation: fileName()` and `Delete FieldRead: Test.FILE_NAME`.

It is easy to have the `Insert Invocation: fileName()`, but I can not collect `Delete FieldRead: Test.FILE_NAME`. Because it is on the line 4 of the original version and I don't know line 4 and line 7 is the same statement.

Could you please tell me how to collect all the change actions on a given statement.

Thank you very much!

Sincerely,
Cuong

**Comment by bqcuong** [comment]
Hi @martinezmatias,

Thank you very much for responding promptly every time 😁.
I found that the changed node of these ops have the same parent node and can be grouped by parent id by following your guide.

Regards,
Cuong

**Comment by martinezmatias** [comment]
Hi @bqcuong 

> I found that the changed node of these ops have the same parent node and can be grouped by parent id by following your guide.

Exact,  that's a way to do that.
Regards
Matias
