### ISSUE TITLE
Gumtree Spoon signaling wrong invocation

### ISSUE THREAD

**Issue by NunoCastanho** [SpoonLabs/gumtree-spoon-ast-diff#139]
Hello, and happy new year.

I have a situation where:
- class A has two methods( `public void move(Number x, Number y)` and `private void move(int x, int y)`)
- class B extends class A
- edit script of adding a method `public void reset()` to B that calls `move(0, 0)`

I was expecting the edit script to be the insertion of the method `reset()` and the insertion of an invocation to `move(Number, Number)` in it. However, it seems to assume the invocation is `move(int, int)`. 

Also, I tested it with the following situation (where there isn't any `move(int, int)` method) and the received the same result.
- class A has one method ( `public void move(Number x, Number y)`)
- class B extends class A
- edit script of adding a method `public void reset()` to B that calls `move(0, 0)`

I verified this by using a visitor that, when it accepts a CtInvocation, prints its executable (`invocation.getExecutable()`).

Am I missing something? Is this a bug? Do I need to supply the file of the superclass (source file of A)? If yes, how do I do so?

Thank you,
Nuno

**Comment by monperrus** [comment]
Hi Nuno, Thanks for the issue. I'm not sure to understand. Would you be able to write a failing test case in a pull-request?

**Comment by NunoCastanho** [comment]
Hey. I've since been able to find what was wrong with it. I wasn't loading the Spoon model completely so it didn't have the necessary information to know the signature of the invoked method.

Thanks!

**Comment by monperrus** [comment]
OK, glad to hear this!
