### ISSUE TITLE
Accessing SPOON_OBJECT of ITree instances

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#144]
I had a question regarding accessing `SPOON_OBJECT` metadata of the ITree instances generated [this way](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/AstComparator.java#L116). I am trying to get the `SPOON_OBJECT` meta data of `scanner.getTree(left)` using `scanner.getTree(left).getMetadata(SpoonGumTreeBuilder.SPOON_OBJECT)` but all I get is `null`.

I need this meta data because I need to pretty-print the ITree after I have made some modifications to its nodes. Can anyone explain how can I access this metadata? Or it the metadata is not being set due to some bug, please let me know how I can go about fixing it.

**Comment by monperrus** [comment]
Thanks for the bug report. Could you provide a failing test case in a pull-request? That would be 
super useful for debugging.

**Comment by martinezmatias** [comment]
As @monperrus says, a test case will help to identify the problem.

I suspect that the problem would be associated to Virtual nodes: Nodes that exist in the GumTree model that are not represented in the Spoon meta-model (there is no 1-to-1 relation between models), such as the node "modifiers" which groups the modifiers of a method.

**Comment by algomaster99** [comment]
**Left program**
```java
package com.diffmin;

import java.util.List;

class Action {
    public static void main(String[] args) {
        System.out.println("Aman Sharma");
    }
}
```

**Right program**
```java
package com.diffmin;

class Action {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
```

I used these files for testing. I will submit them in pull request by today.

**Comment by algomaster99** [comment]
The root of `ITree` nodes does not have a corresponding spoon element so this issue is irrelevant.
