### ISSUE TITLE
Adds a license

### ISSUE THREAD

**Issue by GerardPaligot** [SpoonLabs/gumtree-spoon-ast-diff#15]
That could be a good idea to apply a license on this project.

Why not something like an Apache or MIT license?

**Comment by martinezmatias** [comment]
Hi Gerard
Yes, I agree. Spoon has CeCILL-C. Should we use that one?

**Comment by GerardPaligot** [comment]
As you want but personally, I prefer Apache or MIT licenses because there are more permissive.

**Comment by martinezmatias** [comment]
okey, let's go for any of those, as you prefer (I'm not an expert on the topic). In Astor we have the GNU General Public License.

**Comment by GerardPaligot** [comment]
- MIT: Open source, you don't need to mention the author. You do what you want with the project.
- Apache: Same as MIT but you must mention the author.
- GPL: If you fork, your project must be under GPL license and if you use in another project, it must be an open source project.
- CeCiLL-C: French version of GPL.

PR soon for Apache if it is okay for you.

**Comment by martinezmatias** [comment]
Thanks for the summary. 
> PR soon for Apache if it is okay for you.
great, It's fine for me.
