### ISSUE TITLE
Update gumtree to a version 3.x

### ISSUE THREAD

**Issue by Symbolk** [SpoonLabs/gumtree-spoon-ast-diff#153]
Hi, currently the depending gumtree version is 2.1.2, however, recently gumtree has been updated to 3.0.0 version, though not published on maven central repository any more but on GitHub Packages Entry (https://github.com/orgs/GumTreeDiff/packages?repo_name=gumtree).

Do you have plan to update it the a recent version? Will there be any breaking changes that requires code changes?

**Comment by Symbolk** [comment]
P.S. I encounter some compatible issues when using gumtree 3.0.0 and gumtree-spoon together in the same project, obviously gumtree 3.0.0 introduced breaking API changes, which requires extra code changes to upgrade in gumtree-spoon.

**Comment by monperrus** [comment]
@martinezmatias has a branch with this update to Gumrtree 3x, and confirms that Gumtree 3;x is not backward compatible.

**Comment by martinezmatias** [comment]
Hi @Symbolk 

> gumtree 3.0.0 introduced breaking API changes, which requires extra code changes to upgrade in gumtree-spoon

Yes, a lot of breaking changes.


> has a branch with this update to Gumrtree 3x, 

We will release the new version of gumtree-spoon as soon the version of GumTree 3 is released.  We still have some open issues. 
Additionally, for facilitating the use of GumTree-Spoon, we should wait that a version of GumTree 3 is published (e.g., maven central)

Regards
Matias

**Comment by Symbolk** [comment]
Thanks for the response, @martinezmatias .

However, the owner of Gumtree has confirmed that the artifact won't be released on Maven Central anymore, but Github Packages Registry instead. I have tried and added related guidelines in Wiki.

**Comment by martinezmatias** [comment]
Hi @Symbolk 

> the owner of Gumtree has confirmed that the artifact won't be released on Maven Central anymore
Nice.

> but Github Packages Registry instead.
Actually, I've just noticed that the new version of GT was recently released on GPR, which is a good news for us.

I will work on that on the coming days.

Regards
Matias
