### ISSUE TITLE
`Diff.getRootOperations()` sometimes returns nested operations for updates

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/gumtree-spoon-ast-diff#156]
Hi!

There's a bug in `Diff.getRootOperations()` where sometimes it returns operations on nodes that are direct descendants of nodes in other update operations. I've only found this happen with update operations in particular.

For example, given the following left and right files:

```java
// Left.java
public class Main {
    public void test() {
        int x = 2;
    }
}
```

```java
// Right.java
public class Main {
    public void test() {
        String y = "Updated";
    }
}
```

Yields the following results from `Diff.getRootOperations()` (

```bash
Update LocalVariable at Main:3
        int x = 2 to java.lang.String y = "Updated"
Update TypeReference at Main:3
        int to java.lang.String
Update Literal at Main:3
        2 to "Updated"
```

The cause of this strangeness can be found in `ActionClassifier.getRootActions()`, where there is an implicit assumption that update actions from GumTree are always root operations.

https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/3e392ca49e09a43eb48e618d54bf98a2b97fb99e/src/main/java/gumtree/spoon/diff/ActionClassifier.java#L77-L78

Either there is a bug in GumTree, or this assumption is incorrect.

**Comment by slarse** [comment]
@jrfaller Perhaps you have some insight on this? It looks like the `ActionGenerator` that gumtree-spoon uses has been replaced with `EditScriptGenerator`, but I'm guessing the principles are the same.

**Comment by martinezmatias** [comment]
Hi @slarse 
Yes, indeed the updates are not grouped  and each update operation is considered as an atomic operation that affects a single label.
Regards
Matias

**Comment by martinezmatias** [comment]
Related to https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/125
and https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/114

**Comment by slarse** [comment]
Ah, would you look at that!

Then we can close this issue as a duplicate and continue the discussion in #125

**Comment by martinezmatias** [comment]
Perfect
