### ISSUE TITLE
Generic type modifications in containers like `List` and `Map` are not detected

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#157]
Consider two files whose `Diff` needs to be computed.
**File 1**
```java
import java.util.List;
import java.util.Map;

class Example<A> {
    private List<String> words;
    private Map<A, String> map;
}
```
**File 2**
```java
import java.util.List;
import java.util.Map;

class Example<A, B> {
    private List<? super String> words;
    private Map<A, B> map;
}

```
I expected it would also output `UpdateOperation`s /`InsertOperation` + `DeleteOperation` for changing `String -> ? super String` and `String` -> `B`. However, only one root operation is returned which is:
```
Insert TypeParameter at Example:4
	B
```

**Comment by algomaster99** [comment]
@monperrus @slarse 
**File 1**
```java
import java.util.List;

class Example<A, B> {
    private List<String> words;
}
```
**File 2**
```java
import java.util.List;

class Example<A, B> {
    private List<A> words;
}
```
I looked at the `ITree` model of **File 1** and found that `List` node has no children (I expected `java.lang.String` to be a child) unlike `Example` node which has 3 children and two of them are `A` and `B` (one is the `words` field itself). I think this might be a bug in generating the `ITree` model.

For `private String words`, there are indeed two children - `java.lang.String` and modifier which assures me that the aforementioned case might be a bug. What do you think?

**Comment by monperrus** [comment]
@algomaster99 these are two different cases:

* in `Example<A, B>` the `<A, B>` is a type parameter declaration.
* in `List<A>` the `<A>` is a type parameter usage.

They are conceptually different and modeled differently in Spoon.

That being said, we should capture both in the ITree model, and subsequently in a diff.

The fix should be relatively easy, by changing the gumtree-spoon scanner. Would you give it a try?
