### ISSUE TITLE
travis-ci.org shutting down tomorrow, 15th of June

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/gumtree-spoon-ast-diff#159]
According to a banner on travis-ci.org, it's shutting down tomorrow. This means that CI must be migrated to some other platform ASAP.

![travis-ci-org-shutdown](https://user-images.githubusercontent.com/14223379/121848229-08facd80-ccea-11eb-8cf9-dfb86ec4b25c.png)

**Comment by monperrus** [comment]
In the meantime, we may fly with free credits on travis-ci.com.

I'm doing the change.

**Comment by monperrus** [comment]
We have free credits for the whole SpoonLabs organization.
