### ISSUE TITLE
Incorrect role in parent is returned for `CtWrapper` elements

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#160]
Fetching role of `CtWrapper` elements in their parents returns the element's grandparent's role instead. For example, calling `getRoleInParent` on `final` in `private final int x` returns `CtRole.TYPE_MEMBER` instead of `CtRole.MODIFIER`. This is because parent of `final` is `private final int x` and its role is `CtRole.TYPE_MEMBER`.

The reason for this issue is that the role of `CtWrapper` elements is not set in `NodeCreator.java` as can been for the two lines below.
https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/da117118feace452f60b6383c2d66cddb0b2fe12/src/main/java/gumtree/spoon/builder/NodeCreator.java#L55

https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/da117118feace452f60b6383c2d66cddb0b2fe12/src/main/java/gumtree/spoon/builder/NodeCreator.java#L105

A solution could be to use the [other constructor](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/3e392ca49e09a43eb48e618d54bf98a2b97fb99e/src/main/java/gumtree/spoon/builder/CtWrapper.java#L33) which would set the role as well.

More information: https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/158.

**Comment by algomaster99** [comment]
In addition to `CtWrapper` elements, we will also have to fix this for `CtVirtualElements` as the latter will help us to deal with cases such as:
```diff
class Modifier {
-   int x;
+   private static final int x;
}
```
Since no modifier exists before, a `CtVirtualElement` (a collection element for all modifiers) is added. However, an appropriate role does not exist in `CtRole` enum. Should we create one by the name of `CtRole.MODIFIERS`? (notice the `S`).

**Comment by slarse** [comment]
> Should we create one by the name of `CtRole.MODIFIERS` (notice the `S`)?

There is no singular/plural distinction for roles in Spoon. The role of _all_ modifiers (or any similar collection) is the same as that of a single modifier.

**Comment by algomaster99** [comment]
> There is no singular/plural distinction for roles in Spoon.

Thanks, I did not know that. In that case, we can assign `CtRole.MODIFIER` to `roleInParent` of `CtVirtualElement`.
