### ISSUE TITLE
API for returning children of `CtVirtualElement`

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#162]
From `diffmin`'s point of view, it would be great if I can get children of `CtVirtualElement` - usually modifiers. They would be helpful while setting modifiers on a `CtType` using the `setModifiers` API. This API would be analogous to `CtWrapper`'s `getValue` API.

**Comment by monperrus** [comment]
That would be useful. Would you be able to make a PR?

**Comment by algomaster99** [comment]
Yes, I will be on it :)
