### ISSUE TITLE
Wrapping super types using `CtWrapper` is not required

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#166]
`CtWrapper` is used to wrap elements that are not inherited from `CtElement` and thus, are not a node in spoon metamodel. For example, modifiers are defined as enums in spoon and since diff is calculated on spoon elements, it was necessary to wrap them.

However, consider the following diff:
```diff
- class Child extends Parent1 { }
+ class Child extends Parent2 { }
```

Currently, its edit script contains an update operation for updating the **CtWrapper** to `Parent2`. Instead, I propose that we do not wrap such elements because these are instances of `CtTypeReferences` so the edit script involving these elements can simply say `Update CtTypeReference at Child from Parent1 to Parent2`. The patch to achieve so is:

```diff
diff --git a/src/main/java/gumtree/spoon/builder/NodeCreator.java b/src/main/java/gumtree/spoon/builder/NodeCreator.java
index 19c3cc6..7f10f6f 100644
--- a/src/main/java/gumtree/spoon/builder/NodeCreator.java
+++ b/src/main/java/gumtree/spoon/builder/NodeCreator.java
@@ -102,8 +102,7 @@ public class NodeCreator extends CtInheritanceScanner {
 
         if (reference instanceof CtTypeReference && reference.getRoleInParent() == CtRole.SUPER_TYPE) {
             ITree superType = builder.createNode("SUPER_TYPE", reference.toString());
-            CtWrapper<CtReference> k = new CtWrapper<CtReference>(reference, reference.getParent());
-            superType.setMetadata(SpoonGumTreeBuilder.SPOON_OBJECT, k);
+            superType.setMetadata(SpoonGumTreeBuilder.SPOON_OBJECT, reference);
             reference.putMetadata(SpoonGumTreeBuilder.GUMTREE_NODE, superType);
             builder.addSiblingNode(superType);
         } else {
```

**Comment by algomaster99** [comment]
@monperrus @slarse 

I also had one question regarding the [overridden scanners](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/NodeCreator.java#L78-L97) in `NodeCreator.java`. Why have we _again_ set the metadata for spoon and gumtree nodes using `NodeCreator.scan` when [`createNode`](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/TreeScanner.java#L120) has been called a few statements before?

https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/8066105bd93a793467f554f16e434a86a6f1a592/src/main/java/gumtree/spoon/builder/TreeScanner.java#L45-L49

**Comment by slarse** [comment]
I have no idea, @martinezmatias would probably be the one who knows :)
