### ISSUE TITLE
Proposal to add metamodel property, `simpleName`, in `CtWrapper` elements

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#168]
While dealing with #125 following the solution proposed [here](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/125#issuecomment-864620236), I came across a test case wherein I had to update modifiers. For the rest of the elements, I use an API - `setValueByRole` as illustrated in the comment linked above. However, this wasn't possible for `CtWrapper` elements as its role handler is not registered [here](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/meta/impl/ModelRoleHandlers.java) (this is not expected also).

I am thinking to extend the `CtWrapper` from `CtNamedElementImpl` instead of `CtElementImpl` as this would allow overriding the `simpleName`'s getters and setters and I shall also be able to use `setValueByRole(CtRole.NAME, ModifierKind.<updated value>)` in `diffmin`. Once #166 is resolved, we would only need to bother about modifiers and they do qualify as named elements.

I haven't looked into other alternatives and this is just one way to solve the problem outlined above.

**Comment by algomaster99** [comment]
@monperrus needed your opinion about this issue.

**Comment by monperrus** [comment]
It looks good. If static type checking allows for this with the existing usages of `CtWrapper` and all tests pass, that's likely a easy merge.

**Comment by slarse** [comment]
The one problem I can think of is if we at some point want to wrap an element that is _not_ a named element. Then `CtWrapper` extending `CtNamedElementImpl` becomes a problem, especially as `CtWrapper` is part of GumTree Spoon's public API, and so changing it after the fact would be breaking.

**Comment by algomaster99** [comment]
@slarse After #167, `CtWrapper` is wrapping only one thing - `ModifierKind`. Maybe we should rename the existing class to `CtWrapModifierKind` so that it's more intuitive. And if ever want to wrap some element, we can create a new wrapper. However, I am not sure if that is a great design because it could result in repetitive code. 

Do you have any other ideas on how we can fetch the role? Upon reading the `getValueByRole` implementation, I found out that the element's class must be a `assignableFrom` from one of the classes as mentioned in [roleHandlers](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/meta/impl/ModelRoleHandlers.java#L115). Probably a better way would be to extend this class and add another role handler for `CtWrapper`?

**Comment by slarse** [comment]
> Do you have any other ideas on how we can fetch the role?

You mean from `CtWrapper`? It should reasonably have the same role as the element that it wraps, so just set that role in the `role` field. Isn't that the way it's implemented right now?

**Comment by algomaster99** [comment]
CtWrapper only stores `roleInParent`. We are trying to use `getValueByRole(CtRole.NAME)` on a `CtWrapper` instance and the desired behaviour is to get the name (eg. `"static", "final"`) of the ModifierKind. However, that would not be possible with the current implementation as [`CtNamedElement`/`CtReference` is not assignable from `CtWrapper`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/meta/impl/RoleHandlerHelper.java#L72).

> same role as the element that it wraps

It wraps a `ModifierKind` and since it is not a spoon node, it does not have a role. This would hold true for a `CtClass` instance because I could easily call `CtClass.getValueByRole(CtRole.name)` and get the unqualified name of the class.

**Comment by slarse** [comment]
Seems to me like the simplest way to solve this without locking ourselves in too much in the future is to make `CtWrapper` an interface that extends `CtElement`, rather than a class that extends `CtElementImpl`. Then we can have whatever implementations of `getValueByRole` that we'd like without any clients needing to know about them, it's just `CtWrapper` to them.

**Comment by slarse** [comment]
> We are trying to use getValueByRole(CtRole.NAME) on a CtWrapper

I'm still a little confused by this. Seeing as the elements we wrap in `CtWrapper` are not actually Spoon nodes, and so do not have any contents with roles, what's the semantic meaning behind calling `CtWrapper.getValueByRole(CtRole)`?

**Comment by slarse** [comment]
To be clear, the way I'd imagine CtWrapper to be used would be _given_ some parent element, and something like so:

```java
parent.setValueByRole(wrapper.getRoleInParent(), wrapper.getValue())
```

**Comment by algomaster99** [comment]
This is required for remodelling the `UpdateOperation`. If you look at the solution proposed [here](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/125#issuecomment-864620236), you will see that every update follows a consistent pattern.
1. Generate the patch using `dstNode.getValueByRole(CtRole)`
2. Apply the patch using `srcNode.setValueByRole(CtRole, patch)`

This was not possible for CtWrapper nodes because the wrapped elements aren't really spoon nodes but it was needed because you can have an update from `public` to `private`.

If we want to resolve this, without interfering with `CtWrapper`, we can make an exception in `diffmin` that if we encounter an `srcNode`, which is an instance of `CtWrapper`, we can generate the patch using `getValue` instead and apply it using `setValue` (I thought of this right now).

> To be clear, the way I'd imagine CtWrapper to be used would be given some parent element, and something like so:

We can get the role of a modifier in its parent. That has been fixed in #161 .

**Comment by slarse** [comment]
The element we wrap in a CtWraper is _not_ a proper node in the Spoon AST, and so I don't understand what the intended effect of `CtWrapper.setValueByRole(CtRole, patch)` would be. Could you give a concrete example?

**Comment by algomaster99** [comment]
It would change the name (CtRole.NAME) of the element from `public` to `private`. I tried calling `srcNode. setValueByRole(CtRole, patch)` _after I extended `CtWrapper` from `CtNamedElementImpl`_ and it updated the modifier from `public` to `private`.

**Comment by slarse** [comment]
But that is just an effect in `CtWrapper`. Check the original Spoon AST.

**Comment by algomaster99** [comment]
Okay, I get what you are trying to say. Basically, `setValueByRole` would only change the `simpleName` anyway not the actually wrapped entity.

**Comment by algomaster99** [comment]
> If we want to resolve this, without interfering with CtWrapper, we can make an exception in diffmin that if we encounter an srcNode, which is an instance of CtWrapper, we can generate the patch using `getValue` instead, and apply it using `setValue` (I thought of this right now).

I think this would be a good approach. We even have a reason for the exception because CtWrapper is not a spoon node.

**Comment by slarse** [comment]
> Okay, I get what you are trying to say. Basically, `setValueByRole` would only change the `simpleName` anyway not the actually wrapped entity.

Yes, precisely, with no effect on the original AST. And so it doesn't actually seem useful.

> I think this would be a good approach. We even have a reason for the exception because CtWrapper is not a spoon node.

Yes, I don't really think there's any other choice than that. Although there's no `setValue()` on `CtElement`, so you still need to do something along the lines of what I wrote here: https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/168#issuecomment-898395876. In essence, you can't in general directly modify the wrapped element as it's likely immutable (an enum in this case), you must modify its parent.

**Comment by algomaster99** [comment]
> Although there's no setValue() on CtElement

[`CtWrapper` implements `setValue()` and `getValue()`](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/CtWrapper.java). I think invoking `setValue` on `CtWrapper` should work fine as `value` will just be assigned to a different `ModifierKind`. Don't you think so?

> so you still need to do something along the lines of what I wrote here: #168 (comment).

This will also work indeed.

**Comment by slarse** [comment]
> > Although there's no setValue() on CtElement
> 
> [`CtWrapper` implements `setValue()` and `getValue()`](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/CtWrapper.java). I think invoking `setValue` on `CtWrapper` should work fine as `value` will just be assigned to a different `ModifierKind`. Don't you think so?

No, because modifying the `CtWrapper` element itself does not in any way alter the Spoon AST from which it was built. If you would like that to be the case, then `CtWrapper.setValue` must be altered to look something like this:

```diff
	public void setValue(L wrapped) {
		this.value = wrapped;
+		if (parent != null && roleInParent != null) {
+			parent.setValueByRole(roleInParent, wrapped);
+		}
	}
```

But I'm not sure we want `CtWrapper` to be "that clever".

**Comment by algomaster99** [comment]
> But I'm not sure we want CtWrapper to be "that clever"

Are you saying this because we don't want `CtWrapper` to interfere with Spoon AST? 

> And I think this will actually crash for modifiers as I believe getValueByRole(CtRole.MODIFIER) actually returns all modifiers in a collection. But you get the idea.

Yes, `getValueByRole(CtRole.MODIFIER)` returns a set of modifiers so we cannot _individually_ update modifier. We can either replace the entire collection or we can compare the two collections for what is deleted and what is inserted then just perform operations on them so that `ElementOriginTest` passes.

**Comment by algomaster99** [comment]
> because modifying the CtWrapper element itself does not in any way alter the Spoon AST from which it was built.

Closing this issue.
