### ISSUE TITLE
Question about purpose of `nolabel` property in `TreeScanner`

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#172]
I have noticed a boolean field, `nolabel`, in [TreeScanner](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/TreeScanner.java#L20). From what I have understood. it adds the class name of the node as the label instead of running the label finder and finding its value.

For example, consider `int x = 1` -> `int x = 2`. If `nolabel` is true, one of the mappings is from `Literal` to `Literal` instead of `1` -> `2`. I am not sure what we are achieving here because something which should have been a `diff` is not anymore.

**Comment by slarse** [comment]
I don't know the original intent, but it's useful to be able to see only structural modifications of the AST, disregarding any content changes inside nodes.

**Comment by algomaster99** [comment]
Oh okay. So this will indirectly ignore all the update operations, I think. This was, atleast, true for some of the test cases I tried.
