### ISSUE TITLE
Dependencies are not up to date

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#176]
Some important dependencies need updating.

- Spoon to `9.1.0`
- Junit to version `5`.
   - While we are updating Junit, we can also add hamcrest package. Its assertions messages are clearer.

**Comment by monperrus** [comment]
Activated dependabot, see the flow of PRs :)

**Comment by algomaster99** [comment]
There were a lot of dependencies apparently. I was just looking at the two listed above. Nice!

Anyway, I planned to close this after I upgraded Junit and made the necessary changes to the test suite (would be quite large and split across multiple PRs) but I think that would be better suited to another issue.
