### ISSUE TITLE
bump to Gumtree v3

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/gumtree-spoon-ast-diff#215]
Gumtree v3 s on central, we can upgrade to it

**Comment by algomaster99** [comment]
I will take a look at it sometime next week.

**Comment by monperrus** [comment]
great!

**Comment by martinezmatias** [comment]
I put a reminder in my agenda to work on this issue after the journal deadline.

**Comment by martinezmatias** [comment]
Under working at https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/219

**Comment by algomaster99** [comment]
Resolved by #219 .
