### ISSUE TITLE
duplicated method pair mapping

### ISSUE THREAD

**Issue by oathaha** [SpoonLabs/gumtree-spoon-ast-diff#239]
I am using Spoon AST Diff library to get all method pairs between 2 java files.

Here is the code that I used to get the method pairs

```
    AstComparator  comp = new AstComparator();
    DiffImpl diff = (DiffImpl) comp.compare(new File("a.java"), new File("b.java"));

    Field f = null;

    f = diff.getClass().getDeclaredField("_mappingsComp");
    f.setAccessible(true);
	MappingStore mapping = (MappingStore) f.get(diff);

    Tree dst = mapping.dst;

    for(Tree node: dst.breadthFirst())
    {
        String nodeType = node.getType().toString();
        
        if(!nodeType.equalsIgnoreCase("Method"))
            continue;
        
        CtElement elem = (CtElement) node.getMetadata(SpoonGumTreeBuilder.SPOON_OBJECT);
        
        if(elem != null)
        {
            CtMethod method = retrieveMethod(elem);
            
            if(method != null)
            {
                Tree leftNode = mapping.getSrcForDst(node);
                
                MethodPair methodPair = null;
                
                if(leftNode == null)
                {
                    methodPair = new MethodPair(null, method);
                }
                else
                {
                    CtElement leftElem = (CtElement) leftNode.getMetadata(SpoonGumTreeBuilder.SPOON_OBJECT);
                    CtMethod leftMethod = retrieveMethod(leftElem);
                    
                    methodPair = new MethodPair(leftMethod, method);
                }
                
                if(!changedMethods.containsKey(methodPair))
                {
                    changedMethods.put(methodPair, methodPairOperations);
                }
            }
        }
    }
```

and this code is used to get method content from Spoon object 

```
    private static CtMethod retrieveMethod(CtElement element) 
    {
        if(element == null) 
        {
            return null;
        }
        
        CtMethod method = null;

        if(element instanceof CtMethod) 
        {
            method = (CtMethod) element;
        } 
        
        else 
        {
            method = element.getParent(CtMethod.class);
        }
        
        return method;
	}
```

My expectation is there are mappings between 2 methods of a.java and b.java like this
    a -> a
    b -> b
    c -> c
    empty -> d (where d is added method)

but what I got from GumTreeDiff sometimes looks like this
    a -> a
    a -> b
    b -> b
    b -> d
    c -> c
    empty -> d

As you can see, the mappings of a -> b and b -> d are not correct

To be specific, from the given java files (in form of text file since I cannot upload java file here, a.txt and b.txt), filterMatch() is newly added method which should have mapping pattern like empty -> d.
But what I got is this method is mapped to other methods (such as add()), which is not correct mapping.

Is this mistake due to implementation of Spoon AST Diff or it is from GumTreeDiff algorithm?

[a.txt](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/files/8408294/a.txt)
[b.txt](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/files/8408298/b.txt)

**Comment by monperrus** [comment]
Thanks for the bug report. Could you propose a failing test case in a PR? From there, we'll be able to debug.

**Comment by oathaha** [comment]
From the given java files (in form of text), the below method is added in b.txt

```
@java.lang.SuppressWarnings("unchecked")
private boolean filterMatch(com.google.gerrit.server.CurrentUser user, java.lang.String filter) throws com.google.gwtorm.server.OrmException, com.google.gerrit.server.query.QueryParseException {
    com.google.gerrit.server.query.change.ChangeQueryBuilder qb = args.queryBuilder.create(user);
    com.google.gerrit.server.query.Predicate<com.google.gerrit.server.query.change.ChangeData> p = null;
    if (!(user instanceof com.google.gerrit.server.AnonymousUser)) {
        p = qb.is_visible();
    }
    if (filter != null) {
        qb.setAllowFile(true);
        com.google.gerrit.server.query.Predicate<com.google.gerrit.server.query.change.ChangeData> filterPredicate = qb.parse(filter);
        if (p == null) {
            p = filterPredicate;
        } else {
            p = com.google.gerrit.server.query.Predicate.and(filterPredicate, p);
        }
        p = args.queryRewriter.get().rewrite(p);
    }
    return p == null ? true : p.match(changeData);
}
```

However, this method is mapped with add() method in a.txt, which should not happen

```
@java.lang.SuppressWarnings("unchecked")
private void add(com.google.gerrit.server.mail.ProjectWatch.Watchers matching, com.google.gerrit.server.git.NotifyConfig nc, com.google.gerrit.reviewdb.client.Project.NameKey project) throws com.google.gwtorm.server.OrmException, com.google.gerrit.server.query.QueryParseException {
    for (com.google.gerrit.common.data.GroupReference ref : nc.getGroups()) {
        com.google.gerrit.reviewdb.client.AccountGroup group = com.google.gerrit.common.data.GroupDescriptions.toAccountGroup(args.groupBackend.get(ref.getUUID()));
        if (group == null) {
            com.google.gerrit.server.mail.ProjectWatch.log.warn(java.lang.String.format("Project %s has invalid group %s in notify section %s", project.get(), ref.getName(), nc.getName()));
            continue;
        }
        if (group.getType() != AccountGroup.Type.INTERNAL) {
            com.google.gerrit.server.mail.ProjectWatch.log.warn(java.lang.String.format("Project %s cannot use group %s of type %s in notify section %s", project.get(), ref.getName(), group.getType(), nc.getName()));
            continue;
        }
        com.google.gerrit.server.query.change.ChangeQueryBuilder qb = args.queryBuilder.create(new com.google.gerrit.server.query.change.SingleGroupUser(args.capabilityControlFactory, ref.getUUID()));
        qb.setAllowFile(true);
        com.google.gerrit.server.query.Predicate<com.google.gerrit.server.query.change.ChangeData> p = qb.is_visible();
        if (nc.getFilter() != null) {
            p = com.google.gerrit.server.query.Predicate.and(qb.parse(nc.getFilter()), p);
            p = args.queryRewriter.get().rewrite(p);
        }
        if (p.match(changeData)) {
            recursivelyAddAllAccounts(matching.list(nc.getHeader()), group);
        }
    }
    if (!nc.getAddresses().isEmpty()) {
        if (nc.getFilter() != null) {
            com.google.gerrit.server.query.change.ChangeQueryBuilder qb = args.queryBuilder.create(args.anonymousUser);
            qb.setAllowFile(true);
            com.google.gerrit.server.query.Predicate<com.google.gerrit.server.query.change.ChangeData> p = qb.parse(nc.getFilter());
            p = args.queryRewriter.get().rewrite(p);
            if (p.match(changeData)) {
                matching.list(nc.getHeader()).emails.addAll(nc.getAddresses());
            }
        } else {
            matching.list(nc.getHeader()).emails.addAll(nc.getAddresses());
        }
    }
}
```

Actually, the add() method above is also mapped with the below add() method, which is correct mapping.

```
private void add(com.google.gerrit.server.mail.ProjectWatch.Watchers matching, com.google.gerrit.server.git.NotifyConfig nc, com.google.gerrit.reviewdb.client.Project.NameKey project) throws com.google.gwtorm.server.OrmException, com.google.gerrit.server.query.QueryParseException {
    for (com.google.gerrit.common.data.GroupReference ref : nc.getGroups()) {
        com.google.gerrit.reviewdb.client.AccountGroup group = com.google.gerrit.common.data.GroupDescriptions.toAccountGroup(args.groupBackend.get(ref.getUUID()));
        if (group == null) {
            com.google.gerrit.server.mail.ProjectWatch.log.warn(java.lang.String.format("Project %s has invalid group %s in notify section %s", project.get(), ref.getName(), nc.getName()));
            continue;
        }
        if (group.getType() != AccountGroup.Type.INTERNAL) {
            com.google.gerrit.server.mail.ProjectWatch.log.warn(java.lang.String.format("Project %s cannot use group %s of type %s in notify section %s", project.get(), ref.getName(), group.getType(), nc.getName()));
            continue;
        }
        com.google.gerrit.server.CurrentUser user = new com.google.gerrit.server.query.change.SingleGroupUser(args.capabilityControlFactory, ref.getUUID());
        if (filterMatch(user, nc.getFilter())) {
            recursivelyAddAllAccounts(matching.list(nc.getHeader()), group);
        }
    }
    if (!nc.getAddresses().isEmpty()) {
        if (filterMatch(args.anonymousUser, nc.getFilter())) {
            matching.list(nc.getHeader()).emails.addAll(nc.getAddresses());
        }
    }
}
```

Does this happen due to how algorithm works or it is really bug?

Is it true that one method can have multiple mappings to other methods (as I explained in the first message)?

**Comment by algomaster99** [comment]
Hi @oathaha !

Thanks for your questions. I feel the way you are _translating_ the mapping (from GumTree `ITree` node to `Spoon` element) is incorrect. I have not perused it so I cannot pinpoint where you are going wrong. However, I can answer your questions and also suggest you some solutions to solve your problem.

> Does this happen due to how algorithm works or it is really bug?

There is some mistake in your algorithm.

> Is it true that one method can have multiple mappings to other methods

No (See [section 2](https://dl.acm.org/doi/pdf/10.1145/2642937.2642982)).
  > > There are two constraints for these mappings: a
given node can only belong to one mapping, and mappings
involve two nodes with identical labels.

There is a one-to-one mapping between the nodes. However, there can be some mapping which you do not expect. See an example [here](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/165#issue-941040021). `THEN` is mapped with the wrong `THEN`. This happens because matching is done based on heuristics and computing an exact mapping is an NP-hard problem (could be NP-complete if we already have the mapping). 

> However, this method is mapped with add() method in a.txt, which should not happen

I think methods are mapped here. Instead the annotation (`@java.lang.SuppressWarnings("unchecked")`) above is mapped. Since annotation are also instances of `CtMethod`, you are getting this mapping.

> I am using Spoon AST Diff library to get all method pairs between 2 java files.

We already have a Java class that translates gumtree node mappings to Spoon node mappings. See [SpoonMapping.java](https://github.com/SpoonLabs/diffmin/blob/main/src/main/java/com/diffmin/SpoonMapping.java). I suggest you copy this class in your source project and use `fromGumTreeMapping` to get the spoon mapping. I am planning to port this to GumTree soon, but for now you can just use the class. Also you do not need reflection to get `_mappingsComp`. There is [public method](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/1dece6b9f114e19e7f2f66c6ab7162ce769b97fa/src/main/java/gumtree/spoon/diff/Diff.java#L81) in `Diff` to fetch it for you.

**Comment by algomaster99** [comment]
It is also possible that you are interpreting matching incorrectly. `a -> b` could be `e -> e` where `e` represent the annotation I talked about in the above comment.

**Comment by oathaha** [comment]
Thank you for your answer.

Also, thanks for sharing code for getting method mapping. However, as I see from the SpoonMapping.java, there are only mappings for pairs that both left and right (a,b) are not null. So I think I cannot get methods that are newly added (like in the case that I gave example).

**Comment by algomaster99** [comment]
> that both left and right (a,b) are not null.

Yes, mapping does not intend to return that. Imagine if there are two functions inserted. According to your logic, there will be two instances of `(a,b)` where the `a` value will be `null` and this contradicts the property. A more pragmatic reason is that mapping is supposed to contain AST nodes from two trees that are _similar_. `null` and any ASTNode are not similar because the former has no property that matches that of the `ASTNode`.

To find new methods that are added, you should look at `Diff.getRootOperations()`. This is also called the edit script. It will have an instance of `InsertOperation` whose `srcNode` would be the newly added method.

**Comment by algomaster99** [comment]
@oathaha have I answered your question? If yes, we could close this issue.

**Comment by oathaha** [comment]
Yes. You may close the issue.
