### ISSUE TITLE
Can not  detect the change of Exception type

### ISSUE THREAD

**Issue by Chaz93** [SpoonLabs/gumtree-spoon-ast-diff#24]
The tool does not detect changes in Exception Type.
for example：
```java
public class TestMain {
    static public void main() throws IOException {
        try{
            TestClass.testMethod(1);
        }catch (IllegalArgumentException e){
            e.printStackTrace();
           
        }
    }
}
```
```java
public class TestMain {
    static public void main() throws IOException {
        try{
            TestClass.testMethod(1);
        }catch (NullPointerException e){
            e.printStackTrace();
          
        }
    }
}
```
and I got "no AST change" as Result

**Comment by monperrus** [comment]
fixed in master. thanks a lot for the report.

**Comment by Chaz93** [comment]
Thanks for your reply,but I got ClassNotFoundException after running the program : and Stack is:
Caused by: java.lang.ClassNotFoundException: spoon.compiler.SpoonCompiler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by monperrus** [comment]
This is a classpath problem with Spoon. I recommend to use the last master and Spoon 5.7.
