### ISSUE TITLE
Signature of CtInvocation changed with Spoon 6.0.0

### ISSUE THREAD

**Issue by surli** [SpoonLabs/gumtree-spoon-ast-diff#26]
Gumtree-spoon-ast-diff unit tests are not passing anymore with Spoon 6.0.0 because the printed signature of a CtInvocation node changed.
For example in test7, the following signature is expected:
```java
QuickNotepadTextArea#addKeyListener(QuickNotepad$KeyHandler)
``` 
and the current result is now: 
```java
addKeyListener(QuickNotepad$KeyHandler)
```

In other word, the declaring type is not printed anymore before the signature of the executable.
I do not know if it's a problem that should be reported to Spoon, or if we need to change the tests here. 
WDYT?

**Comment by monperrus** [comment]
We can also slightly change the way we construct the labels of those nodes to add again the
declaring class.

**Comment by surli** [comment]
> We can also slightly change the way we construct the labels of those nodes to add again the declaring class.

Indeed. I just don't know if it's something we might need back in Spoon or not.

**Comment by monperrus** [comment]
fixed by https://github.com/SpoonLabs/gumtree-spoon-ast-diff/commit/bc910341d41dc5bb3e82cb956655bc93c5fa17e0
