### ISSUE TITLE
Offsets are all zeros [0,0]

### ISSUE THREAD

**Issue by pouryafard75** [SpoonLabs/gumtree-spoon-ast-diff#323]
Hello, I am just getting started with Spoon.

I am trying to add GT-Spoon as one of the tools for our [DiffBenchmark](https://github.com/pouryafard75/DiffBenchmark). However, I stumbled upon a problem which is having zeros as all the offsets. Our benchmark is originally built for gumtree-jdt visitor but we want to find the eqv subtree for other visitors by relying on the offsets.

I have tried the ASTComperator with the [annotation example](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/tree/master/src/test/resources/examples/annotations), and tried to print the generated trees using the following code:
```
MappingStore mappingsComp = result.getMappingsComp();
		System.out.println(mappingsComp.src.toTreeString());
		System.out.println(mappingsComp.dst.toTreeString());
```
However the offsets are all shown as zero:
```
root [0,0]
    RootPac: unnamed package [0,0]
        Class: Test [0,0]
            Method: hashCode [0,0]
                RETURN_TYPE: int [0,0]
                Modifiers_Method [0,0]
                    Modifier: public [0,0]
                Annotation: java.lang.Override [0,0]
                Return: return [0,0]
                    UnaryOperator: NEG [0,0]
                        Literal: 1 [0,0]
root [0,0]
    RootPac: unnamed package [0,0]
        Class: Test [0,0]
            Method: hashCode [0,0]
                RETURN_TYPE: int [0,0]
                Modifiers_Method [0,0]
                    Modifier: public [0,0]
                Annotation: java.lang.Deprecated [0,0]
                Return: return [0,0]
                    UnaryOperator: NEG [0,0]
                        Literal: 1 [0,0]
```

**Comment by algomaster99** [comment]
Hi! Thanks for the bug report! It seems that we don't support node position in the tree created using Gumtree APIs even though Gumtree provides with APIs such as `.setPos` and `.setLength`.

May I ask what kind of position are you interested in? Should it be line number-based or column-based?

**Comment by pouryafard75** [comment]
I would like to have the exact offsets similar to the way that GT jdt visitor provides. [Startoffset-EndOffset]

**Comment by algomaster99** [comment]
I believe I could add integers returned by these [two APIs](https://github.com/INRIA/spoon/blob/c60af45512223894e32a5fd2963079a88d22c388/src/main/java/spoon/reflect/cu/SourcePosition.java#L74-L82) then. I understand that it gives the index of start and end character.

**Comment by pouryafard75** [comment]
That would be perfect.

**Comment by algomaster99** [comment]
> work because the position was from [NoSourcePosition](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/cu/position/NoSourcePosition.java?rgh-link-date=2024-09-18T21%3A13%3A06Z)

That would be the case for implicit elements like default constructor, but for other elements, it should work. Gumtree tree based on Spoon should not contain implicit elements in my opinion. It is a good point and I will add a test for it.
