### ISSUE TITLE
Returning Null pointer at CtFieldAccess.getTarget()

### ISSUE THREAD

**Issue by Erlonidas** [SpoonLabs/gumtree-spoon-ast-diff#338]
I'm generating some AST diffs of methods from a dataset. Part of the code runs normally, but sometimes I encounter this error:
![image](https://github.com/user-attachments/assets/5fb605af-e887-426a-ad09-88425767aebb)

The error (NullPointerException: Cannot invoke "spoon.reflect.code.CtExpression.isImplicit()" might be cause the return value of "spoon.reflect.code.CtFieldAccess.getTarget()" is null) indicateing that the Spoon library is processing a null value when it shouldn't be, specifically when calling the getTarget() method on a CtFieldAccess object.

This type of error occurs when some part of the code doesn't handle a null value appropriately while working with Spoon's AST (Abstract Syntax Tree).

**Comment by monperrus** [comment]
thanks for the bug report

https://github.com/INRIA/spoon/pull/6103 is a longer term fix.
