### ISSUE TITLE
Use the role in the parent instead of the type 

### ISSUE THREAD

**Issue by tdurieux** [SpoonLabs/gumtree-spoon-ast-diff#39]
I was thinking that maybe we will obtain better results if we use the role in the parent to label each node instead of the class.
Because what matter is the role stay consistent the the type of element can change.

Ex:
```diff
-            yearOfEra,
+            (era == GregorianCalendar.AD ? yearOfEra : 1 - yearOfEra),
```

Currently, this operation will be tagged as delete + insert because `yearOfEra` is a CtVariableAccess and `(era == GregorianCalendar.AD ? yearOfEra : 1 - yearOfEra)` is a CtConditional.
The two type does not match and is thus not considered as an update.

WDYT?

**Comment by monperrus** [comment]
Interesting. Do you mean using the role as node type?

**Comment by tdurieux** [comment]
Yes

**Comment by monperrus** [comment]
Excellent idea. Would you give it a try?
