### ISSUE TITLE
NullPointerException because the typeAccess.getAccessedType() is null

### ISSUE THREAD

**Issue by Symbolk** [SpoonLabs/gumtree-spoon-ast-diff#40]
Hi, when I am processing a java file with gumtreespoon, I find that for some files the _visitCtTypeAccess()_ in LabelFinder.java throws _NullPointerException_, and the reason is that the _typeAccess.getAccessedType()_ returns null but it calls _getQualifiedName()_. 

Sorry I am not allowed to upload the java file that triggers the bug, but you can find it in AOSP(Google Android Open Source Project), the file is \base\core\java\android\widget\ImageView.java)

**Comment by monperrus** [comment]
Thanks a lot for the bug report. Would you make a pull request to fix it?

--Martin

**Comment by monperrus** [comment]
Thanks for the bug report!
