### ISSUE TITLE
What is the difference between gumtree-spoon-ast-diff and gumtreediff?

### ISSUE THREAD

**Issue by Symbolk** [SpoonLabs/gumtree-spoon-ast-diff#41]
Hi there,

I found the 2 most-starred AST diff tools on github 2 months ago, and had been developing applications on top of them.

I noticed that though the two tools belong to different accounts, the author seems to be the same person---**Prof. Jean-Rémy Falleri**

Firstly, I managed to integrate gumtree-spoon-ast-diff into my application, because I only need to handle Java files and it is smaller than gumtreediff. However, I spotted a number of bugs and exceptions in using it, some of them lies in the dependencies(spoon, eclipse jdt, etc.) while others lies in the tool itself. I fixed few of them, though trying my best(as a student).

Afterwards I turn to gumtreediff for help, which supports multiple languages and shows to be more robust. For now it works well, and I have figured out its workflow for Java files. But since I need to make more modifications on it, I want to learn more about it, like:

* _What is the main difference between gumtree-spoon-ast-diff and gumtreediff?(Except for language support and backend parser)_
* _Is the gumtree-spoon-ast-diff still under development?_
* _What's the advantage of spoon comparing with JavaParser and JDT?_

Thanks to all~

**Comment by monperrus** [comment]
> Is the gumtree-spoon-ast-diff still under development?

Yes, see https://github.com/SpoonLabs/gumtree-spoon-ast-diff/commits/master

> What is the main difference between gumtree-spoon-ast-diff and gumtreediff?

Two differences:

* The tree of gumtree-spoon-ast-diff is carefully designed to provide better AST diffs for Java as opposed to vanilla gumtreediff. You can compare the AST diffs on your own data.
* The diff always points to the original Spoon node that can be pretty-printed or further analyzed

> What's the advantage of spoon comparing with JavaParser and JDT?

The API for each AST node is more comprehensive and easier to use, see https://github.com/INRIA/spoon/issues/1303

**Comment by monperrus** [comment]
> I fixed few of them

That's great, would you propose your fixes as pull-request?

**Comment by monperrus** [comment]
Closing, please comment even if closed
