### ISSUE TITLE
Test 25008: Update Vs Insert/Delete

### ISSUE THREAD

**Issue by surli** [SpoonLabs/gumtree-spoon-ast-diff#42]
I had difficult time with test 25008 in #27 and apparently we now got the old behaviour back... 

See: https://ci.inria.fr/sos/job/gumtree-spoon-ast-diff/559/

So what should be the ground truth on that specific test? Should it be a delete/insert or an update?

**Comment by monperrus** [comment]
As far as I remember, update is better. I really would like to understand what triggers the
behavioral change.

**Comment by surli** [comment]
> I really would like to understand what triggers the behavioral change.

I investigate a bit on it yesterday.
I really think that the problem is something really tricky and not directly linked with Spoon: 
  - the bug is reproducible only when launching the entire unit test,
  - the bug does not occur when launching the entire unit test in debug mode, even without any breakpoint
  - sometimes, when changing some lines in the code and not compiling it entirely, it does not occur anymore

So I'm thinking about a bug related either with one java optimization somewhere (like the bug we found with @danglotb on Dspot due to the optimization of the try/catch) or related with the loading order of the classes.
I think changing the version of Spoon just changed one of those element and which led to the other behaviour.

However I really don't know how to debug as I don't manage to reproduce the bug with the debugger...

**Comment by monperrus** [comment]
thanks for the analysis.

then I propose to remove this test case.

**Comment by surli** [comment]
To remove it or to mark it as ignored?

**Comment by monperrus** [comment]
to ignore it with a fat comment explaining the problem.

**Comment by monperrus** [comment]
closed per 6cefcbbe06c2ddd9a886c5fb5028d1708b13b67c
