### ISSUE TITLE
Case Coderep Dataset 1806

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/gumtree-spoon-ast-diff#52]
The case Dataset 1 of coderep 1806 .
The diff 1806 only updates an import.
However, GTSpoon shows different changes.
The problem is that it detects all the Updates on the field reads which types were involved in the modified import.

**Comment by tdurieux** [comment]
I don't know if it is a bug or if it is what we want.

(Ps:I think there are more than 1500 patches in CodRep that only changes an import)

**Comment by martinezmatias** [comment]
Hi Thomas,

> I don't know if it is a bug or if it is what we want.
I complete agree. Per se, it's not a bug of Gumtree.  Maybe there are some node in the GTSpoon granularity that we can avoid.

Maybe the solution will be part of an implementation of a change clustering.

**Comment by tdurieux** [comment]
It would be nice yo have this abstraction.

You can have for 

- import
- variable rename
- method rename
- add/remove precondition
- ...

But I don't think it's easy to do ...

**Comment by martinezmatias** [comment]
We can discuss to do something.
I have to check the bibliography. A paper that we have recently discuss is:
https://dl.acm.org/citation.cfm?doid=3238147.3238219

**Comment by monperrus** [comment]
This is what we want. Gumtree-Spoon goes beyond the syntactic tokens, it captures the semantics (the
called code in this example).
