### ISSUE TITLE
How to obtain pre- and post-version of commonAncestor()?

### ISSUE THREAD

**Issue by chenzimin** [SpoonLabs/gumtree-spoon-ast-diff#56]
Hi,

Let us assume that we have the following two java files:

add_pre.java:
```java
public class foo{
    public int add(int x, int y){
        return(x-y);
    }
}
```

add_post.java:
```java
public class foo{
    public int add(int x, int y){
        return(x+y);
    }
}
```

How I obtained the diff:
```java
Diff diff = new AstComparator().compare(new File("add_pre.java"), new File("add_post.java"));
CtElement method = diff.commonAncestor();
while(!(method instanceof CtMethod)){
    method = method.getParent();
}
```

How can I get the pre- and post-version of CtMethod `method`? One way that I found is to swap the arguments to compare():
```java
Diff diff = new AstComparator().compare(new File("add_post.java"), new File("add_pre.java"));
```
Are there any other easier way to do it?

Thanks!

**Comment by martinezmatias** [comment]
Hi @chenzimin 
I had a very similar problem and I have done some workaround outside the project.
I have some solutions in mind, and I could integrate one of them. 
Let me check what can we do.
Regards
Matias

**Comment by martinezmatias** [comment]
Hi @chenzimin 
I create a first version of the feature you need.
I pushed a test case to show how to use it.
 https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/60/commits/7f7fb1c07c150c6a5a06d1425979bc5603025364 
What do you think? Is the fuctionality you need? If you think it's ok, I proceed with the merge.
Regards
Matias

**Comment by chenzimin** [comment]
LGTM, thanks for providing the functionality!

**Comment by martinezmatias** [comment]
Great, if you need some modifications, dont hesitate to write me.
