### ISSUE TITLE
No diff when reading Java from .txt file

### ISSUE THREAD

**Issue by chenzimin** [SpoonLabs/gumtree-spoon-ast-diff#58]
Hi,

If we have `add_pre.txt` & `add_pre.java`  with the same content. And `add_post.txt` & `add_post.java` with the same content.

Executing:
 ```java
Diff diff = new AstComparator().compare(new File("add_pre.txt"), new File("add_post.txt"));`
```
cause `diff.getAllOperations().size()` to be zero 

While executing:
 ```java
Diff diff = new AstComparator().compare(new File("add_pre.java"), new File("add_post.java"));`
```
will have non-zero `diff.getAllOperations().size()`

It is nothing serious but worth pointing out. Any explanation for this kind of behavior?

**Comment by monperrus** [comment]
> Any explanation for this kind of behavior?

Yes. JDT does not parse files ending with `.txt`

Thanks for the note!
