### ISSUE TITLE
Detects no changes when adding 'throws Exception'

### ISSUE THREAD

**Issue by chenzimin** [SpoonLabs/gumtree-spoon-ast-diff#59]
Hi,

Let us assume that we have the following two java files:

foo_pre.java:
```java
class foo{
    public static void main(String[] args) {}
}
```

foo_post.java:
```java
class foo{
    public static void main(String[] args) throws Exception {}
}
```

gumtree-spoon-ast-diff does not detect any changes, is it a bug?

**Comment by martinezmatias** [comment]
Hi @chenzimin 

> gumtree-spoon-ast-diff  does not detect any changes, is it a bug?

I think so. I realized of that this week by analyzing yours datasets CodeRep.   
I also found it does not detect changes on generic types.
