### ISSUE TITLE
Detects a method as Updated and on the same time as Inserted

### ISSUE THREAD

**Issue by digeo** [SpoonLabs/gumtree-spoon-ast-diff#64]
Hello, I am processing two revisions of a Java file ([rev. 1](https://www.dropbox.com/s/4pn0kdkjo4fnkzn/FileCleaner%281%29f732c9a50cbaf0675e8b1846c8d3480c06f297a2.java?dl=0) and [rev. 2](https://www.dropbox.com/s/opzdzb2ulfmvuc2/FileCleaner%282%299c18390762527fe8d1bf7af8ded586566cdbb59c.java?dl=0)) with [Gumtree Spoon AST Diff](https://mvnrepository.com/artifact/fr.inria.gforge.spoon.labs/gumtree-spoon-ast-diff/1.6).

```
File fl = new File("src/test/resources/FileCleaner(1)f732c9a50cbaf0675e8b1846c8d3480c06f297a2.java");
File fr = new File("src/test/resources/FileCleaner(2)9c18390762527fe8d1bf7af8ded586566cdbb59c.java");

Diff result = new AstComparator().compare(fl, fr);
List<Operation> operations = result.getAllOperations();
for (Operation operation : operations) {

   CtElement element = (CtElement) operation.getAction().getNode().getMetadata(SpoonGumTreeBuilder.SPOON_OBJECT);
   String nodeType = element.getClass().getSimpleName();
   nodeType = nodeType.substring(2, nodeType.length() - 4);

   if (Objects.equals(nodeType, "Method")) {
      if (operation.getAction() instanceof Insert) {
         InsertOperation insertOperation = new InsertOperation((Insert) operation.getAction());
         System.out.println(insertOperation);
      }
      else if (operation.getAction() instanceof Update) {
         UpdateOperation updateOperation = new UpdateOperation((Update) operation.getAction());
         System.out.println(updateOperation);
      }
   }
}
```
When I execute the above snippet, it returns the method: exitWhenFinished Updated and on the same time Inserted. But this is not true, since the method does not exist on [rev. 1](https://www.dropbox.com/s/4pn0kdkjo4fnkzn/FileCleaner%281%29f732c9a50cbaf0675e8b1846c8d3480c06f297a2.java?dl=0).
Am I doing something wrong or is there a bug?
Thank you in advance!

**Comment by monperrus** [comment]
Thanks for the report, could you create a failing test in a pull request?
