### ISSUE TITLE
Feature Request: modify the ast trees with changes

### ISSUE THREAD

**Issue by 11510746** [SpoonLabs/gumtree-spoon-ast-diff#67]
#### Feature Desciption
I get a change list after calling AstComparator.compare method.  Assume I want to modify the left ast tree, which means I may replace some change nodes with the corresponding nodes in the the right ast  tree. 

Then, I want to generate a new .java file from the modified ast tree.

How can I do this based on current version gumtree-spoon-ast-diff?

**Comment by tdurieux** [comment]
It is possible If you do something like this:

```java
final Diff result = new AstComparator().compare(file1, file2);
Factory factory = result. commonAncestor().getFactory();

factory.getEnvironment().setPrettyPrinterCreator(() ->
    new SniperJavaPrettyPrinter(factory.getEnvironment(), new File("").getAbsolutePath())
);
CtClass type = result.commonAncestor().getParent(CtClass.class);
List<Operation> opertations = result.getAllOperations()
for (Operation op: opertations) {
    op.getSrcNode().replace(op. getDstNode());
}

PrettyPrinter printer = launcher.getEnvironment().createPrettyPrinter();
printer.calculate(factory.CompilationUnit().getOrCreate(type), Arrays.asList(type));
String output = printer.getResult();
System.out.println(output);
```

This code replaces all the nodes from the left with the right and prints the class.

**Comment by 11510746** [comment]
Could you please update the spoon-core version to the newest? Some features in the code you provide above only exist in the newest version.

![spoon](https://user-images.githubusercontent.com/23020574/53283314-839d2900-377f-11e9-9f69-6f739408366f.png)

**Comment by 11510746** [comment]
Could you please update the spoon-core version to the newest? Some features in the code you provide above only exist in the newest version.
![spoon](https://user-images.githubusercontent.com/23020574/53283322-a8919c00-377f-11e9-9c57-bad6f5c6cfb3.png)

**Comment by 11510746** [comment]
> It is possible If you do something like this:
> 
> ```java
> final Diff result = new AstComparator().compare(file1, file2);
> Factory factory = result. commonAncestor().getFactory();
> 
> factory.getEnvironment().setPrettyPrinterCreator(() ->
>     new SniperJavaPrettyPrinter(factory.getEnvironment(), new File("").getAbsolutePath())
> );
> CtClass type = result.commonAncestor().getParent(CtClass.class);
> List<Operation> opertations = result.getAllOperations()
> for (Operation op: opertations) {
>     op.getSrcNode().replace(op. getDstNode());
> }
> 
> PrettyPrinter printer = launcher.getEnvironment().createPrettyPrinter();
> printer.calculate(factory.CompilationUnit().getOrCreate(type), Arrays.asList(type));
> String output = printer.getResult();
> System.out.println(output);
> ```
> 
> This code replaces all the nodes from the left with the right and prints the class.

I met some problems and as below. Could you please help me solve it?

**Comment by monperrus** [comment]
Thanks for the follow-up. Bumped to 7.3.0 see #68
