### ISSUE TITLE
Duplicate operations in `Diff.getAllOperations()`

### ISSUE THREAD

**Issue by 11510746** [SpoonLabs/gumtree-spoon-ast-diff#69]
Some of the root operations are duplicated

<img width="947" alt="2019-03-03 5 48 00" src="https://user-images.githubusercontent.com/23020574/53693687-ec6b4d80-3dde-11e9-9de3-9872ecd290ff.png">

**Comment by tdurieux** [comment]
In your screenshot you are showing the elements in all operations instead of root operations. Is it on purpose?

**Comment by 11510746** [comment]
> In your screenshot you are showing the elements in all operations instead of root operations. Is it on purpose?

Both root operations and all operations are complete, the next property is _mappingsComp, not belonged to root operations.

**Comment by 11510746** [comment]
#### input
file 1

```java
public class test{
    void main(){
        System.out.println("move");
    }

    void method(){
        System.out.println("origin");
    }

    void delete(){

    }
}
```

file 2

```java
public class test{
    void main(){
        print();
    }

    void print(){
        System.out.println("move");
    }

    void method(){
        System.out.println("update");
    }
}
```

#### Code
```java
AstComparator diff = new AstComparator();
        //spoon CtClass or the spoon tree root node ???
        CtElement left = diff.getCtType(new File("input/operations/test1.java"));
        CtElement right = diff.getCtType(new File("input/operations/test2.java"));

        Diff editScript = diff.compare(left, right);
        List<Operation> rootOp = editScript.getRootOperations();
        List<Operation> allOp = editScript.getAllOperations();
        MappingStore ms = editScript.getMappingsComp();
```

**Comment by monperrus** [comment]
Thanks for the report, could you create a failing test in a pull request?

**Comment by 11510746** [comment]
> Thanks for the report, could you create a failing test in a pull request?

https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/70
