### ISSUE TITLE
A possible typo in LabelFinder.java

### ISSUE THREAD

**Issue by ITWOI** [SpoonLabs/gumtree-spoon-ast-diff#76]
Hi,

I found that  [LabelFinder.java#L77](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/ade625225902c5e300532e4ba940e61012d87d23/src/main/java/gumtree/spoon/builder/LabelFinder.java#L77)  may be a typo. Should it be "continue"?

**Comment by monperrus** [comment]
you're right! could you make a pull-request to fix it?

Thanks!

**Comment by ITWOI** [comment]
I have made a PR for it. Please refer to #77.
