### ISSUE TITLE
question: what is the definition of root operations?

### ISSUE THREAD

**Issue by 11510746** [SpoonLabs/gumtree-spoon-ast-diff#78]
when I diff the following code, I found there are 2 operations on the same node from different granularities (**the second operation seems a sub-operation of the first one**). What I want is something like `delete method sub; insert method mul` or `update method sub to mul`. 

## root operations I got
<img width="433" alt="1" src="https://user-images.githubusercontent.com/23020574/54979501-4629f680-4fde-11e9-820e-fef4dd15949a.png">

## origin
```java
public class Calculator {
    public static int add(int a, int b){
        return a + b;
    }

    public static int sub(int a, int b){
        return a-b;
    }
}
```

## modified
```java
public class Calculator {
    public static int add(int a, int b){
        return a + b;
    }

    public static int mul(int a, int b){
        return a*b;
    }

    public static double div(int a, int b){
        return 1.0*a/b;
    }
}
```

**Comment by monperrus** [comment]
Thanks for the bug report. Could you create a pull-request with a failing test case?

**Comment by martinezmatias** [comment]
The current implementation of the action classifier (which decides which action is Root and which one is not root) does not consider Update. The original classifier was defined in Gumtree and we reuse it.
We should maybe discuss about the root definition and write it in the doc. 
IMHO, Those two updates are 'independent', but I am not sure if that case should be consider as a bug or not.

**Comment by 11510746** [comment]
> The current implementation of the action classifier (which decides which action is Root and which one is not root) does not consider Update. The original classifier was defined in Gumtree and we reuse it.
> We should maybe discuss about the root definition and write it in the doc.
> IMHO, Those two updates are 'independent', but I am not sure if that case should be consider as a bug or not.

So if I want to remove the `sub-operation` mentioned above, how can I do?
Can I customize an action classifier or use `CtElement#getElements(Filter<E> filter` to fulfill my need?
Could you pls give me some effective approach or suggestions?

**Comment by 11510746** [comment]
> The current implementation of the action classifier (which decides which action is Root and which one is not root) does not consider Update. The original classifier was defined in Gumtree and we reuse it.
> We should maybe discuss about the root definition and write it in the doc.
> IMHO, Those two updates are 'independent', but I am not sure if that case should be consider as a bug or not.

After reviewing the code of `ActionClassifier# getRootActions`, I find update actions in `srcUpdTrees` are added without any unconditionally. 
```java
/**
	 * This method retrieves ONLY the ROOT actions
	 */
	public List<Action> getRootActions() {
		final List<Action> rootActions = srcUpdTrees.stream().map(t -> originalActionsSrc.get(t))
				.collect(Collectors.toList());

		rootActions.addAll(srcDelTrees.stream() //
				.filter(t -> !srcDelTrees.contains(t.getParent()) && !srcUpdTrees.contains(t.getParent())) //
				.map(t -> originalActionsSrc.get(t)) //
				.collect(Collectors.toList()));

		rootActions.addAll(dstAddTrees.stream() //
				.filter(t -> !dstAddTrees.contains(t.getParent()) && !dstUpdTrees.contains(t.getParent())) //
				.map(t -> originalActionsDst.get(t)) //
				.collect(Collectors.toList()));

		rootActions.addAll(dstMvTrees.stream() //
				.filter(t -> !dstMvTrees.contains(t.getParent())) //
				.map(t -> originalActionsDst.get(t)) //
				.collect(Collectors.toList()));

		rootActions.removeAll(Collections.singleton(null));
		return rootActions;
	}
```

In this case, I guess it thinks a method update and its statement update are independent, because the definition of the method update may be detecting a change of method signature that is nothing to do with method statements. 

But in the aspect of AST node, the nodes of the two updates have subordination relationship. Users can get both updates from the super AST node. Therefore, I think keeping the updated AST sub-node is a little bit redundant, especially when they want to apply operations on AST according the root operations.

**Comment by martinezmatias** [comment]
Hi @11510746 

> But in the aspect of AST node, the nodes of the two updates have subordination relationship. Users can get both updates from the super AST node. Therefore, I think keeping the updated AST sub-node is a little bit redundant, especially when they want to apply operations on AST according the root 

I will check that with my colleagues. 

> Could  you pls give me some effective approach or suggestions?

A workaround could be to process the output. I imagine a simple post-processor:
For each operation, you take the node and you check that there is no parent of that node and is affected by other operation: if at least parent  is affected, then you discard it as root. (Not sure if it correctly works)

**Comment by 11510746** [comment]
> The current implementation of the action classifier (which decides which action is Root and which one is not root) does not consider Update. The original classifier was defined in Gumtree and we reuse it.
> We should maybe discuss about the root definition and write it in the doc.
> IMHO, Those two updates are 'independent', but I am not sure if that case should be consider as a bug or not.

After reviewing the code of `ActionClassifier# getRootActions`, I find update actions in `srcUpdTrees` are added without any unconditionally. 
```java
/**
	 * This method retrieves ONLY the ROOT actions
	 */
	public List<Action> getRootActions() {
		final List<Action> rootActions = srcUpdTrees.stream().map(t -> originalActionsSrc.get(t))
				.collect(Collectors.toList());

		rootActions.addAll(srcDelTrees.stream() //
				.filter(t -> !srcDelTrees.contains(t.getParent()) && !srcUpdTrees.contains(t.getParent())) //
				.map(t -> originalActionsSrc.get(t)) //
				.collect(Collectors.toList()));

		rootActions.addAll(dstAddTrees.stream() //
				.filter(t -> !dstAddTrees.contains(t.getParent()) && !dstUpdTrees.contains(t.getParent())) //
				.map(t -> originalActionsDst.get(t)) //
				.collect(Collectors.toList()));

		rootActions.addAll(dstMvTrees.stream() //
				.filter(t -> !dstMvTrees.contains(t.getParent())) //
				.map(t -> originalActionsDst.get(t)) //
				.collect(Collectors.toList()));

		rootActions.removeAll(Collections.singleton(null));
		return rootActions;
	}
```

In this case, I guess it thinks a method update and its statement update are independent, because the definition of the method update may be detecting a change of method signature that is nothing to do with method statements. 

But in the aspect of AST node, the nodes of the two updates have subordination relationship. Users can get both updates from the super AST node. Therefore, I think keeping the updated AST sub-node is a little bit **redundant**, especially when they want to apply operations on AST according the root operations.

Could you pls give me some `effective` suggestions on how to remove the update operation with a updated sub-node?

**Comment by 11510746** [comment]
> A workaround could be to process the output. I imagine a simple post-processor:
> For each operation, you take the node and you check that there is no parent of that node and is affected by other operation: if at least parent is affected, then you discard it as root. (Not sure if it correctly works)

#### A suggestion
Maybe the fields of `gumtree.spoon.diff.ActionClassifier` can be set as `protect`, so that users can `extends` it to custom their action classifier.

**Comment by martinezmatias** [comment]
Dear @11510746 
We have analyzed the case two mention.
Our classifier does not group those Update changes according to the parent's affected.
The Root classifier only aims at grouping inserts and/or delete.
For instance, imagine that you add a node N with 3 children (C1, C2, C3).
So, the root operation only will show one Operation: Insert N.
if we consider all the operations, we have 4: one insert for N and one insert for each child.
Similar case for deletion.
However, the classifier does not aim at grouping updates. That should be a post process of the results according to your needs.
Regards
Matias
