### ISSUE TITLE
feat: Compare AST modulo identifier

### ISSUE THREAD

**Issue by nharrand** [SpoonLabs/gumtree-spoon-ast-diff#80]
It would be nice to be able to compare AST, without having names impacting the results.
It could be useful to detect clones, or to compare decopiled code.

**Comment by martinezmatias** [comment]
Hi @nharrand 

> It would be nice to be able to compare AST, without having names impacting the results.

Yes, I will be a nice feature. I have some other applications about that feature.
I can implement one workaround to doing that. Let me check if it works.

**Comment by nharrand** [comment]
Maybe we could just override `LabelFinder`

We could override these methods:
```java
	@Override
	public void scanCtNamedElement(CtNamedElement e) {
		label = e.getSimpleName();
	}

	@Override
	public <T> void scanCtVariableAccess(CtVariableAccess<T> variableAccess) {
		label = variableAccess.getVariable().getSimpleName();
}
```
With a global dictionary and a deterministic scheme to create names.

**Comment by martinezmatias** [comment]
I am doing something similar

**Comment by martinezmatias** [comment]
(Testing right now heheh)

**Comment by martinezmatias** [comment]
The idea is to put as Label the Node type

**Comment by nharrand** [comment]
And a unique number?

**Comment by martinezmatias** [comment]
> And a unique number?

It could work. Do you mean a unique number per different Node value?

**Comment by martinezmatias** [comment]
Now, I put in the Node value the type instead of the result got from the LabelFinder

**Comment by martinezmatias** [comment]
So, that forces to match node with the same type.

**Comment by nharrand** [comment]
Yes. Hopefully
```java
int i = 0;
i++;
```
and
```java
int num = 0;
num++;
```
would be equivalent but different from
```java
int num = 0;
i++;
```

**Comment by martinezmatias** [comment]
Exact, for the moment, the test cases focus on renaming

**Comment by martinezmatias** [comment]
it seems to work, lets see on more complex cases what happens

**Comment by martinezmatias** [comment]
I will push soon.
(In the project we dont have command line parser, so, this hard to activate the option)

**Comment by nharrand** [comment]
Currently I am using `new AstComparator().compare(original,actual);`, so any alternative API member would do fine for me.

**Comment by martinezmatias** [comment]
I commit. It's a draft version. It does not include to pass the option via command line. (I open a new issue for that)

**Comment by nharrand** [comment]
That's super cool! Thanks a lot!

**Comment by martinezmatias** [comment]
Hi @nharrand 
Merge. Note that it's the first version and probably we need to doing some tuning. (in addition to the option to activate it, now it uses system.property, which is not the most elegant.
Here one test cases https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/java/gumtree/spoon/AstComparatorTest.java#L1633

**Comment by martinezmatias** [comment]
BTW, I will be in KTH next May, we can discuss about!

**Comment by nharrand** [comment]
Awesome! See you there then.
Meanwhile I'll try your solution!
