### ISSUE TITLE
[Important] Bug inducing Fix

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/gumtree-spoon-ast-diff#84]
One of the changes introduces a bug (or at least a strange situation) such as "empty" Insert operations with Null nodes. i.e., we dont know the node that is inserted.

The problem is here:
https://github.com/SpoonLabs/gumtree-spoon-ast-diff/commit/4899ca0f7103b709d427cf677382a5047ad02470#diff-009fc305480e133b71e1bbe2ddadac09L29

There, it was removed one line that associates a Tree node with the corresponding Spoon node. Thus, GumTree detects changes on its model (the Tree) that has not any Spoon element associated.

**Comment by martinezmatias** [comment]
bug exposing test in brach https://github.com/SpoonLabs/gumtree-spoon-ast-diff/tree/bugissue84

**Comment by martinezmatias** [comment]
IMO, we should revert those changes:
https://github.com/SpoonLabs/gumtree-spoon-ast-diff/commit/4899ca0f7103b709d427cf677382a5047ad02470#diff-009fc305480e133b71e1bbe2ddadac09L29

**Comment by monperrus** [comment]
This is because we don't have a one-to-one relationship between Spoon nodes and Gt nodes (some Gt nodes are artificial, they don't originally exist in the Spoon Tree).

As a result, the toString message of Gt-Spoon was super confusing (see the issue for that change + + my long hour of debugging).

Now, there may be an alternative by restoring the previous association, but then we need to rework on the toString representation.

**Comment by martinezmatias** [comment]
> As a result, the toString message of Gt-Spoon was super confusing (see the issue for that change + + my long hour of debugging).

I agree.


> This is because we don't have a one-to-one relationship between Spoon nodes and Gt nodes (some Gt nodes are artificial, they don't originally exist in the Spoon Tree).

That's correct. The problem that we had previous to the mentioned changes is that we created one GT node for each modifier but, at the same time, the associated to each of them the *list* of modifier. As consequence, the resulting AST had redundant information. Note that we cannot associate the ITree  to a modifier because the type of the modifier are ModifierKind, which is not a CTElement.

**Comment by martinezmatias** [comment]
A potential solution could be:
Each time we create a ITree node (i.e., GT model) that corresponds to an object *Ob* from the Spoon's model that does **not** inherit from CtElement (e.g., the enumerations such as Modifiers), we create a Wrapper that a) extends CtElementImp b) references to an object (*Ob* ).
As consequence, the operators could reference to this wrapper and, by transition, to the modifier.

**Comment by monperrus** [comment]
very good idea.

**Comment by martinezmatias** [comment]
Fixed
