### ISSUE TITLE
Throw exception when insert `static` at a method head

### ISSUE THREAD

**Issue by 11510746** [SpoonLabs/gumtree-spoon-ast-diff#86]
#### Input
```java
AstComparator comp = new AstComparator();
        Diff diff = comp.compare("public class Calculator {\n" +
                "    public int add(int a, int b){\n" +
                "        return a + b;\n" +
                "    }\n" +
                "}", "public class Calculator {\n" +
                "    public static int add(int a, int b){\n" +
                "        return a + b;\n" +
                "    }\n" +
                "}");
```

#### Result
The operation `Delete class` is wrong since the class name is not changed!

The move operation is wired and throws exception!

<img width="1205" alt="Screen Shot 2019-04-08 at 4 12 48 PM" src="https://user-images.githubusercontent.com/23020574/55708831-7da29500-5a19-11e9-8e81-76e2ace81855.png">

**Comment by monperrus** [comment]
Thanks, could you add this failing test case in a pull request?

**Comment by 11510746** [comment]
> Thanks, could you add this failing test case in a pull request?

https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/87
