### ISSUE TITLE
question: combine the operation pair (insert, move) when insert a `CtBinaryOperator`

### ISSUE THREAD

**Issue by 11510746** [SpoonLabs/gumtree-spoon-ast-diff#91]
When I **INSERT** or **DELETE** a BinaryOperator, it always come along with a **MOVE** operation. So why not combine them as a Update operation?

### Example
input
```java
class Tmp{
     int test(){
          int a = 0;
          return 3 + a;
     }
}

class Tmp{
     int test(){
          int a = 0;
          return 3 + a + 4;
     }
}
```

output

<img width="623" alt="Screen Shot 2019-04-10 at 7 51 31 PM" src="https://user-images.githubusercontent.com/23020574/55876977-702d0c80-5bcb-11e9-9b33-01105ebe97cd.png">

**Comment by martinezmatias** [comment]
Hi @11510746 
IMHO, the output seems Ok.
My supposition about why it's correct: the new Binary is inserted by operation id 0. The binary has an operator + and a right operant "4". Then, the other operation, id 1 (move) moves  the existing binary operation (3+ a) to the Left part of the inserted operator (id 0). So, it's seem fine the output.
Cheers
Matias
