### ISSUE TITLE
Modifiable without children

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/gumtree-spoon-ast-diff#92]
In our model, we add a GumTree  node named Modifiers_X, which groups the modifiers of a Modifiable element.
However, if that element does not have modifiers, the GT node Modifiers is empty.
So, in branch https://github.com/SpoonLabs/gumtree-spoon-ast-diff/tree/emptymodifiable I propose to avoid creating such elements, with the goal of creating smaller trees, and consequently faster matchings.
By contrary, we loose *explicit* information in our model (i.e., the Modifiable element does not have any modifier).
WDYT?
If you agree, we create a PR from that branch.

**Comment by monperrus** [comment]
LGTM.
